name: "Neolink"
description: "Will run Neolink directly as Add-on in HAOS"
version: "0.0.5"
slug: "neolink"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
  - armv7
ports:
  19554/tcp: 19554
map:
  - config:rw
options:
  mode: mqtt
schema:
  mode: list(rtsp|mqtt|dual)
