name: Generic Proxy
version: 1.2
panel_icon: "mdi:server-network-outline"
panel_title: Nginx Proxy Manager
slug: generic-proxy
description: Generic Proxy addon
url: "https://github.com/rpruden/hassio-addons/"
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5500]/"
watchdog: "http://[HOST]:[PORT:5500]/"
ingress: true
ingress_port: 5500
ingress_entry: /
panel_admin: false
ports:
  5500/tcp: 5500
ports_description:
  5500/tcp: Web interface (not required for Home Assistant Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://server.local:5500"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
